/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-gogo.
// source: api.proto
// DO NOT EDIT!

/*
	Package corestats is a generated protocol buffer package.

	It is generated from these files:
		api.proto

	It has these top-level messages:
		Usage
		PodUsage
		ContainerUsage
		StatsResponse
		StatsRequest
*/
package corestats

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Usage struct {
	CpuUsageCoreNanoSeconds    uint64 `protobuf:"varint,1,opt,name=cpu_usage_core_nano_seconds,json=cpuUsageCoreNanoSeconds,proto3" json:"cpu_usage_core_nano_seconds,omitempty"`
	MemoryWorkingSetBytes      uint64 `protobuf:"varint,2,opt,name=memory_working_set_bytes,json=memoryWorkingSetBytes,proto3" json:"memory_working_set_bytes,omitempty"`
	EphemeralStorageUsageBytes uint64 `protobuf:"varint,3,opt,name=ephemeral_storage_usage_bytes,json=ephemeralStorageUsageBytes,proto3" json:"ephemeral_storage_usage_bytes,omitempty"`
}

func (m *Usage) Reset()                    { *m = Usage{} }
func (*Usage) ProtoMessage()               {}
func (*Usage) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{0} }

func (m *Usage) GetCpuUsageCoreNanoSeconds() uint64 {
	if m != nil {
		return m.CpuUsageCoreNanoSeconds
	}
	return 0
}

func (m *Usage) GetMemoryWorkingSetBytes() uint64 {
	if m != nil {
		return m.MemoryWorkingSetBytes
	}
	return 0
}

func (m *Usage) GetEphemeralStorageUsageBytes() uint64 {
	if m != nil {
		return m.EphemeralStorageUsageBytes
	}
	return 0
}

type PodUsage struct {
	Name       string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace  string            `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Usage      *Usage            `protobuf:"bytes,3,opt,name=usage" json:"usage,omitempty"`
	Containers []*ContainerUsage `protobuf:"bytes,4,rep,name=containers" json:"containers,omitempty"`
}

func (m *PodUsage) Reset()                    { *m = PodUsage{} }
func (*PodUsage) ProtoMessage()               {}
func (*PodUsage) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{1} }

func (m *PodUsage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PodUsage) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *PodUsage) GetUsage() *Usage {
	if m != nil {
		return m.Usage
	}
	return nil
}

func (m *PodUsage) GetContainers() []*ContainerUsage {
	if m != nil {
		return m.Containers
	}
	return nil
}

type ContainerUsage struct {
	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Usage *Usage `protobuf:"bytes,2,opt,name=usage" json:"usage,omitempty"`
}

func (m *ContainerUsage) Reset()                    { *m = ContainerUsage{} }
func (*ContainerUsage) ProtoMessage()               {}
func (*ContainerUsage) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{2} }

func (m *ContainerUsage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ContainerUsage) GetUsage() *Usage {
	if m != nil {
		return m.Usage
	}
	return nil
}

// StatsResponse is sent by plugin to kubelet in response to StatsRequest RPC
type StatsResponse struct {
	Node *Usage      `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
	Pods []*PodUsage `protobuf:"bytes,2,rep,name=pods" json:"pods,omitempty"`
}

func (m *StatsResponse) Reset()                    { *m = StatsResponse{} }
func (*StatsResponse) ProtoMessage()               {}
func (*StatsResponse) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{3} }

func (m *StatsResponse) GetNode() *Usage {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *StatsResponse) GetPods() []*PodUsage {
	if m != nil {
		return m.Pods
	}
	return nil
}

// StatsRequest is the empty request message for Kubelet
type StatsRequest struct {
}

func (m *StatsRequest) Reset()                    { *m = StatsRequest{} }
func (*StatsRequest) ProtoMessage()               {}
func (*StatsRequest) Descriptor() ([]byte, []int) { return fileDescriptorApi, []int{4} }

func init() {
	proto.RegisterType((*Usage)(nil), "corestats.Usage")
	proto.RegisterType((*PodUsage)(nil), "corestats.PodUsage")
	proto.RegisterType((*ContainerUsage)(nil), "corestats.ContainerUsage")
	proto.RegisterType((*StatsResponse)(nil), "corestats.StatsResponse")
	proto.RegisterType((*StatsRequest)(nil), "corestats.StatsRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CoreStats service

type CoreStatsClient interface {
	Get(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type coreStatsClient struct {
	cc *grpc.ClientConn
}

func NewCoreStatsClient(cc *grpc.ClientConn) CoreStatsClient {
	return &coreStatsClient{cc}
}

func (c *coreStatsClient) Get(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	out := new(StatsResponse)
	err := grpc.Invoke(ctx, "/corestats.CoreStats/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CoreStats service

type CoreStatsServer interface {
	Get(context.Context, *StatsRequest) (*StatsResponse, error)
}

func RegisterCoreStatsServer(s *grpc.Server, srv CoreStatsServer) {
	s.RegisterService(&_CoreStats_serviceDesc, srv)
}

func _CoreStats_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreStatsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/corestats.CoreStats/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreStatsServer).Get(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CoreStats_serviceDesc = grpc.ServiceDesc{
	ServiceName: "corestats.CoreStats",
	HandlerType: (*CoreStatsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _CoreStats_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func (m *Usage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Usage) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.CpuUsageCoreNanoSeconds != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintApi(dAtA, i, uint64(m.CpuUsageCoreNanoSeconds))
	}
	if m.MemoryWorkingSetBytes != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintApi(dAtA, i, uint64(m.MemoryWorkingSetBytes))
	}
	if m.EphemeralStorageUsageBytes != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintApi(dAtA, i, uint64(m.EphemeralStorageUsageBytes))
	}
	return i, nil
}

func (m *PodUsage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PodUsage) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintApi(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Namespace) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintApi(dAtA, i, uint64(len(m.Namespace)))
		i += copy(dAtA[i:], m.Namespace)
	}
	if m.Usage != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintApi(dAtA, i, uint64(m.Usage.Size()))
		n1, err := m.Usage.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.Containers) > 0 {
		for _, msg := range m.Containers {
			dAtA[i] = 0x22
			i++
			i = encodeVarintApi(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *ContainerUsage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ContainerUsage) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintApi(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if m.Usage != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintApi(dAtA, i, uint64(m.Usage.Size()))
		n2, err := m.Usage.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	return i, nil
}

func (m *StatsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StatsResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Node != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintApi(dAtA, i, uint64(m.Node.Size()))
		n3, err := m.Node.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if len(m.Pods) > 0 {
		for _, msg := range m.Pods {
			dAtA[i] = 0x12
			i++
			i = encodeVarintApi(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *StatsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StatsRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func encodeFixed64Api(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Api(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintApi(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Usage) Size() (n int) {
	var l int
	_ = l
	if m.CpuUsageCoreNanoSeconds != 0 {
		n += 1 + sovApi(uint64(m.CpuUsageCoreNanoSeconds))
	}
	if m.MemoryWorkingSetBytes != 0 {
		n += 1 + sovApi(uint64(m.MemoryWorkingSetBytes))
	}
	if m.EphemeralStorageUsageBytes != 0 {
		n += 1 + sovApi(uint64(m.EphemeralStorageUsageBytes))
	}
	return n
}

func (m *PodUsage) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovApi(uint64(l))
	}
	l = len(m.Namespace)
	if l > 0 {
		n += 1 + l + sovApi(uint64(l))
	}
	if m.Usage != nil {
		l = m.Usage.Size()
		n += 1 + l + sovApi(uint64(l))
	}
	if len(m.Containers) > 0 {
		for _, e := range m.Containers {
			l = e.Size()
			n += 1 + l + sovApi(uint64(l))
		}
	}
	return n
}

func (m *ContainerUsage) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovApi(uint64(l))
	}
	if m.Usage != nil {
		l = m.Usage.Size()
		n += 1 + l + sovApi(uint64(l))
	}
	return n
}

func (m *StatsResponse) Size() (n int) {
	var l int
	_ = l
	if m.Node != nil {
		l = m.Node.Size()
		n += 1 + l + sovApi(uint64(l))
	}
	if len(m.Pods) > 0 {
		for _, e := range m.Pods {
			l = e.Size()
			n += 1 + l + sovApi(uint64(l))
		}
	}
	return n
}

func (m *StatsRequest) Size() (n int) {
	var l int
	_ = l
	return n
}

func sovApi(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozApi(x uint64) (n int) {
	return sovApi(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Usage) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Usage{`,
		`CpuUsageCoreNanoSeconds:` + fmt.Sprintf("%v", this.CpuUsageCoreNanoSeconds) + `,`,
		`MemoryWorkingSetBytes:` + fmt.Sprintf("%v", this.MemoryWorkingSetBytes) + `,`,
		`EphemeralStorageUsageBytes:` + fmt.Sprintf("%v", this.EphemeralStorageUsageBytes) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PodUsage) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PodUsage{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Namespace:` + fmt.Sprintf("%v", this.Namespace) + `,`,
		`Usage:` + strings.Replace(fmt.Sprintf("%v", this.Usage), "Usage", "Usage", 1) + `,`,
		`Containers:` + strings.Replace(fmt.Sprintf("%v", this.Containers), "ContainerUsage", "ContainerUsage", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ContainerUsage) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ContainerUsage{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Usage:` + strings.Replace(fmt.Sprintf("%v", this.Usage), "Usage", "Usage", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *StatsResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&StatsResponse{`,
		`Node:` + strings.Replace(fmt.Sprintf("%v", this.Node), "Usage", "Usage", 1) + `,`,
		`Pods:` + strings.Replace(fmt.Sprintf("%v", this.Pods), "PodUsage", "PodUsage", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *StatsRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&StatsRequest{`,
		`}`,
	}, "")
	return s
}
func valueToStringApi(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Usage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Usage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Usage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CpuUsageCoreNanoSeconds", wireType)
			}
			m.CpuUsageCoreNanoSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CpuUsageCoreNanoSeconds |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemoryWorkingSetBytes", wireType)
			}
			m.MemoryWorkingSetBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MemoryWorkingSetBytes |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EphemeralStorageUsageBytes", wireType)
			}
			m.EphemeralStorageUsageBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EphemeralStorageUsageBytes |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PodUsage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PodUsage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PodUsage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Namespace", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Namespace = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Usage", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Usage == nil {
				m.Usage = &Usage{}
			}
			if err := m.Usage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Containers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Containers = append(m.Containers, &ContainerUsage{})
			if err := m.Containers[len(m.Containers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ContainerUsage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ContainerUsage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ContainerUsage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Usage", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Usage == nil {
				m.Usage = &Usage{}
			}
			if err := m.Usage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StatsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StatsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StatsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Node", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Node == nil {
				m.Node = &Usage{}
			}
			if err := m.Node.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pods", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pods = append(m.Pods, &PodUsage{})
			if err := m.Pods[len(m.Pods)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StatsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StatsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StatsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipApi(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowApi
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthApi
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowApi
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipApi(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthApi = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowApi   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("api.proto", fileDescriptorApi) }

var fileDescriptorApi = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xcd, 0x6e, 0xd4, 0x30,
	0x10, 0x5e, 0x77, 0x53, 0x44, 0xa6, 0x50, 0x21, 0x23, 0xd4, 0xb0, 0x94, 0xa8, 0x8a, 0x10, 0xf4,
	0xc2, 0x56, 0x5a, 0x0e, 0x08, 0xc4, 0x85, 0xf6, 0xd0, 0x0b, 0x42, 0x28, 0x2b, 0xc4, 0x8d, 0xc8,
	0x9b, 0x1d, 0xd2, 0x15, 0xc4, 0x63, 0x6c, 0x47, 0xa8, 0x37, 0x1e, 0x81, 0x37, 0xe0, 0x59, 0xb8,
	0xf5, 0xc8, 0x91, 0x23, 0x5d, 0x5e, 0x04, 0x79, 0x4c, 0x97, 0x20, 0x56, 0x3d, 0xc5, 0x33, 0xdf,
	0xcf, 0x7c, 0xf1, 0x18, 0x52, 0x65, 0x16, 0x63, 0x63, 0xc9, 0x93, 0x4c, 0x6b, 0xb2, 0xe8, 0xbc,
	0xf2, 0x6e, 0xf4, 0xb0, 0x59, 0xf8, 0x93, 0x6e, 0x36, 0xae, 0xa9, 0x3d, 0x68, 0xa8, 0xa1, 0x03,
	0x66, 0xcc, 0xba, 0x77, 0x5c, 0x71, 0xc1, 0xa7, 0xa8, 0x2c, 0xbe, 0x09, 0xd8, 0x7c, 0xed, 0x54,
	0x83, 0xf2, 0x19, 0xdc, 0xa9, 0x4d, 0x57, 0x75, 0xa1, 0xa8, 0x82, 0x5f, 0xa5, 0x95, 0xa6, 0xca,
	0x61, 0x4d, 0x7a, 0xee, 0x32, 0xb1, 0x27, 0xf6, 0x93, 0x72, 0xa7, 0x36, 0x1d, 0xd3, 0x8f, 0xc8,
	0xe2, 0x4b, 0xa5, 0x69, 0x1a, 0x61, 0xf9, 0x18, 0xb2, 0x16, 0x5b, 0xb2, 0xa7, 0xd5, 0x27, 0xb2,
	0xef, 0x17, 0xba, 0xa9, 0x1c, 0xfa, 0x6a, 0x76, 0xea, 0xd1, 0x65, 0x1b, 0x2c, 0xbd, 0x15, 0xf1,
	0x37, 0x11, 0x9e, 0xa2, 0x3f, 0x0c, 0xa0, 0x7c, 0x0e, 0x77, 0xd1, 0x9c, 0x60, 0x8b, 0x56, 0x7d,
	0xa8, 0x9c, 0x27, 0x1b, 0xc6, 0xc7, 0x10, 0x51, 0x3d, 0x64, 0xf5, 0x68, 0x45, 0x9a, 0x46, 0x0e,
	0xa7, 0x60, 0x8b, 0xe2, 0xab, 0x80, 0xab, 0xaf, 0x68, 0x1e, 0x7f, 0x43, 0x42, 0xa2, 0x55, 0x8b,
	0x9c, 0x37, 0x2d, 0xf9, 0x2c, 0x77, 0x21, 0x0d, 0x5f, 0x67, 0x54, 0x8d, 0x9c, 0x26, 0x2d, 0xff,
	0x36, 0xe4, 0x7d, 0xd8, 0xe4, 0x79, 0x3c, 0x69, 0x6b, 0x72, 0x63, 0xbc, 0xba, 0xcc, 0x31, 0x5b,
	0x96, 0x11, 0x96, 0x4f, 0x00, 0x6a, 0xd2, 0x5e, 0x2d, 0x34, 0x5a, 0x97, 0x25, 0x7b, 0xc3, 0xfd,
	0xad, 0xc9, 0xed, 0x1e, 0xf9, 0xe8, 0x02, 0x8c, 0xaa, 0x1e, 0xb9, 0x78, 0x01, 0xdb, 0xff, 0xa2,
	0x6b, 0x63, 0xae, 0x82, 0x6c, 0x5c, 0x1a, 0xa4, 0x78, 0x0b, 0xd7, 0xa7, 0xa1, 0x5b, 0xa2, 0x33,
	0xa4, 0x1d, 0xca, 0x7b, 0x90, 0x68, 0x9a, 0x47, 0xb3, 0x75, 0x3a, 0x46, 0xe5, 0x03, 0x48, 0x0c,
	0xcd, 0xc3, 0x3a, 0x42, 0xf2, 0x9b, 0x3d, 0xd6, 0xc5, 0xe5, 0x95, 0x4c, 0x28, 0xb6, 0xe1, 0xda,
	0x1f, 0xff, 0x8f, 0x1d, 0x3a, 0x3f, 0x39, 0x86, 0x34, 0xac, 0x9b, 0x7b, 0xf2, 0x29, 0x0c, 0x8f,
	0xd1, 0xcb, 0x9d, 0x9e, 0xbc, 0x4f, 0x1e, 0x65, 0xff, 0x03, 0x31, 0x65, 0x31, 0x38, 0xdc, 0x3d,
	0x3b, 0xcf, 0xc5, 0x8f, 0xf3, 0x7c, 0xf0, 0x79, 0x99, 0x8b, 0xb3, 0x65, 0x2e, 0xbe, 0x2f, 0x73,
	0xf1, 0x73, 0x99, 0x8b, 0x2f, 0xbf, 0xf2, 0xc1, 0xec, 0x0a, 0xbf, 0xc8, 0x47, 0xbf, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x52, 0xce, 0xd1, 0xc1, 0xd8, 0x02, 0x00, 0x00,
}
